---
title: "Second Model"
author:
  - name: Hakan Egeli
  - name: Soumyendu Sarkar
date: 'April 21, 2018'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include = FALSE}

# load the project. This will autoload the data and also create training and test datasets
library('ProjectTemplate')
load.project()

```

```{r, echo=FALSE}
ggplot(dataset, aes(x = AvgDaysOfPayCategory, y = CreditLimit, fill = AvgDaysOfPayCategory)) + 
  geom_boxplot(outlier.color = 'blue', outlier.shape = 1) +
  scale_y_log10() +
  stat_summary(fun.y = mean, geom = "point", shape = 1, size = 1, color = "white") +
  theme(legend.position = "") +
  ggtitle('Avg Days of Pay vs Credit Limit') +
  xlab('Avg Days of Pay') + 
  ylab('Credit Limit')
```

```{r, echo=FALSE}
ggplot() + 
  geom_histogram(aes(ZeroMinScale(dataset$SalesLastYr, na.rm = TRUE)), bins = 40) +
  ggtitle('Avg Days of Pay vs Credit Limit') +
  xlab('Avg Days of Pay') + 
  ylab('Credit Limit')
```

```{r, echo=FALSE}
library(rpart)
model <- rpart(CreditLimit ~ ., data = dataset_train, control = rpart.control(cp = 0.005))
```

```{r, echo=FALSE}

library(rattle)
fancyRpartPlot(model)

#plot(model)
#text(model, use.n = T)
```

```{r, echo=FALSE}

summary(model)

```

```{r, echo=FALSE}

model <- rpart(CreditLimit ~ DesignBandSalesLast12Mo + AvgDaysOfPayCategory + SalesLastYr + TotalSalesLast12Mo + AlternativeMetalSalesLast12Mo + MedianIncomeHouseholds + SalesCurrentYr + PlainBandSalesLast12Mo + MedianEarnings + RuralUrbanContinuumCode, data = dataset_train, control = rpart.control(cp = 0.015))

```


```{r, echo=FALSE}

fancyRpartPlot(model)

```

```{r, echo=FALSE}

model <- rpart(CreditLimit ~ DesignBandSalesLast12Mo + AvgDaysOfPayCategory + SalesLastYr + TotalSalesLast12Mo + AlternativeMetalSalesLast12Mo + SalesCurrentYr + PlainBandSalesLast12Mo + MedianEarnings, data = dataset_train, control = rpart.control(cp = 0.0125))

```

```{r, echo=FALSE}

fancyRpartPlot(model)

```

```{r, echo=FALSE}

summary(model)

```

```{r, echo=FALSE}

aggregate(DesignBandSalesLast12Mo ~ CreditLimit, data = dataset_train, FUN = length)

```

```{r, echo=FALSE}
dataset_train_alt <- dataset_train

dataset_train_alt$CreditLimit <- factor(dataset_train_alt$CreditLimit) 

model <- rpart(CreditLimit ~ DesignBandSalesLast12Mo + SalesLastYr + TotalSalesLast12Mo + AlternativeMetalSalesLast12Mo + SalesCurrentYr + PlainBandSalesLast12Mo, data = dataset_train_alt, control = rpart.control(cp = 0.005), method="class")

```

```{r, echo=FALSE}

fancyRpartPlot(model)

# pdf("tree.pdf")
# fancyRpartPlot(model)
# dev.off()

```

```{r, echo=FALSE}

plotcp(model)

```

```{r, echo=FALSE}
model$cptable[which.min(model$cptable[,"xerror"]),"CP"]

printcp(model)
#model <- prune(model, cp = model$cptable[which.min(model$cptable[,"xerror"]),"CP"])

#fancyRpartPlot(model, uniform=TRUE, main="Pruned Classification Tree")

```

```{r, echo=FALSE}

model <- lm(formula = CreditLimit ~ DesignBandSalesLast12Mo + AvgDaysOfPay + SalesLastYr + TotalSalesLast12Mo + AlternativeMetalSalesLast12Mo + MedianIncomeHouseholds + SalesCurrentYr + PlainBandSalesLast12Mo + MedianEarnings + RuralUrbanContinuumCode, data = dataset_train)

```


```{r, echo=FALSE}

summary(model)

```


```{r, echo=FALSE}

model <- lm(formula = CreditLimit ~ AvgDaysOfPay + MedianIncomeHouseholds + SalesCurrentYr + MedianEarnings, data = dataset_train)

```


```{r, echo=FALSE}

summary(model)

```

```{r, echo=FALSE}

model <- lm(formula = CreditLimit ~ (DesignBandSalesLast12Mo + SalesLastYr + AlternativeMetalSalesLast12Mo + SalesCurrentYr + PlainBandSalesLast12Mo + AlternativeMetalSalesLast12Mo:PlainBandSalesLast12Mo), data = dataset_train)

```


```{r, echo=FALSE}

summary(model)

```

```{r, echo=FALSE}

library(VGAM)

```

```{r, echo=FALSE}

dataset_train_alt <- dataset_train

dataset_train_alt$CreditLimit <- factor(dataset_train_alt$CreditLimit) 

model <- vglm(CreditLimit ~ SalesLastYr + PlainBandSalesLast12Mo, family = multinomial, data = dataset_train_alt)

```

```{r, echo=FALSE}

summary(model)

```


