---
title: 'Formal Problem Statement'
author:
  - name: Hakan Egeli
  - name: Soumyendu Sarkar
date: 'April 26, 2018'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), '../reports/', '01-FPS.html')) })
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "..")
```

# Executive Summary

Benchmark is a U.S. based jewelry manufacturer that primarily focuses on wedding rings. As a manufacturer, Benchmark sells to retailers and wholesalers but not directly to consumers.

Purpose of this project is to examine if a model can be developed to assist Benchmark with assesing the credit risk of potential new customers (retailers) and help Benchmark assign credit limits for those new customers. This credit limit establishes how much a retailer can purcase from the manufacturer without making a payment for the duration of their payment term (usually Net 30).

The **missed opportunity** for Benchmark is:

- Failure to do business with a retail store customer for erroneous risk assessment is loss of opportunity to make money
- Failure to offer right credit line to the retail store, before payments are settled, may result in loss of profit
 
Currently, between 35% to 45% of customers are assigned a fixed lower credit limit and their accounts are not revised unless the retailer requests it. Assigning correct credit limits could potentially mean higher sales for some of these customers and this could also reduce the default losses for those where only the Credit Rating information was used to make their credit limit determination.

If we can develop a way to determine how much credit can be extended to a customer, then we can increase Benchmark's market share, and their profits while we reduce the customer default risk.

# Problem

Oftentimes closing a sales depends on the look, touch and feel of the actual product, therefore, retailers do have to make purchases from the manufacturer before they make an actual sale to a consumer and this requires a considerable investment by the retailer. 

To alleviate the problem, the manufacturer offers payment terms where an immediate payment is not required from the retailer. But that poses a potential financial risk to the manufacturer since every retailers ability to pay their bills vary; the store may default on payment, or the store may go out of business without returning the jewellery. Establishing a credit limit for the retailers mitigates this problem by limiting the risk for the manufacturer and allowing the retailers to make a purchase without paying for it up front.

Determining the right credit limit amount, which reduces the manufacturer's risk and maximizes the retailer's purchasing power which directly impacts the store sales, depend on many factors and business intuition. At this time, there is no exact formula which can be applied to determine credit limits for potential customers.

# Project

At Benchmark, determining credit limits is done through the Jewelers Board of Trade's (JBT) credit rating system. JBT provides commercial credit information, collections, marketing services, and statistics on thousands of jewelry retailers, wholesalers and manufacturers but does not make credit recommendations. Each JBT member makes their own determination how to use this data and Benchmark does the same by assigning credit limits based on these ratings and other sales related factors.

The purpose of this project is to build a model which can make a credit limit determinatin for a customer. The project plans to do this by examining correlations between the credit limits and other factors such as credit ratings, past sales history, and market data for the existing customers so that a model can be build where all the relationships and business intuition is incapsulated.

## Scope

The model will be limited to estimate the risk and credit lines for smaller jewellery store customers who are in vast majority.

For bigger retailers like Amazon and Zales the business model is different. Also data points are very different which likely will not help making a robust model.

## Model Usage

Model will be primarily used by the sales managers of Benchmark and the president who is an engineer himself and shows keen interest.

Once the model is deployed and validated, model will quantify the risk assessment based on the model inference, and a credit line to customers will be determined. 

This is quite a shift from the sales management team having a free reign in determining the risks and credit worthiness of the customers. It will likely have some resentment. But the president of Benchmark Rings is on board and driving this change. 

## Stakeholders

We have identified the Management, Sales Manager, Sales Team, and the Marketing Manager as the key stakeholders for this project.

* Management; President of Benchmark
* Sales Manager; determine credit limits for customers and will be responsible vetting the proposed model
* Sales team; provide the necessary data during the prospect development as an input to the model
* Marketing Manager; obtain relavant demographic/census information related to the retailers and the markets where the retailers are located

## Objectives

* Establish a reliable model that determines a credit limit for a new customer.
* Be able to do these predictions based on data that can be obtained relatively easy from the potential customer and from publicly avaiable market data.
* Make the model easily accessible to the sales team so that they use this model to assign credit limits instead of manually assigning one.

## Critical Success Factors

### Project Success Metrics

We will consider this project a success if we can reduce customer defaults without reducing sales. The metric which we will use to evaluate this are:

a. Accounts Receivable Turnover KPI; 20% or more improvement, reduction in defaults or collections.
b. Sales Growth Metric; 7% to 10% expected annual growth plus a 10% increase

Because a credit limit on a retailer can reduce the sales potential of that retailer while it reduces the risk on the seller, these two metricies will give us the insight to the avoided risk and the impact on the overall sales.

### Model Success Metrics

Assigning higher credit limits to customers could result in higher defaults or collections and conversely, assigning lower credit limits could potentially reduce sales, therefore the model has to be accurate. Eventhough the overall accuracy of the model is important, the model has to achive certain percentage of accuracy detecting True Positives and True Negatives for each credit limit class. We will use the Accuracy metric to evalue the success of the model as well as the Sensitivity (or Recall) and the Specificity of the model. 

We will consider the model a success if

a. Overall Accuracy 90% or better
b. Sensitivity (or Recall) 90% or better
c. Specificity 80% or better

## Risks

If the **Project Success Metrics** are not met, then the client will go back to determining credit limits based on business intuition by the Admin team. Losses will be limited to the project development and the difference between the sales gains and the default losses, which will be closely monitored using the Accounts Receivable Turnover KPI metric and the Sales Growth Metric.

If the **Model Success Metrics** is not met, then the client will use this model as a guidence to their manual decision making process until a better model is developed.

**Adoption Failure** by the organization is also a concern. During initial deployment of the model, a human vetting of model decision will help alleviate concerns and likely generate more confidence in model performance. This will be done by evaluating the model performance with new data every week and the model will be updated with version control.

## Requirements

1. List of Customers who have purchased products during the last and this callendar year, their JBT account number and location information .

2. Monthly JBT ratings for the current customers to calculate the credit limits.

3. Sales and Payment aggregates for the customers going back a year.

4. Market Data, potential size of the market, size of the supply, expected growth, etc. to supplement the sales and payment data.

## Delivery/Deployment

Ease of use and access to the model is critical for the acceptance of the solution. Currently, all the customer, prospect data and the sales history for the current customers reside in a cloud-based ERP system (NetSuite). A web based solution where the two systems integrate is desirable. The web based system shall:

a. Accept customer data export from the ERP system into the model to perfom predictions
b. Allow sales reps to obtain one-off credit limits for potential new customers while they are travelling to sign customers

## Project Plan

We will perform the following major project tasks to complete the project

* Formalize the Problem - Est. 1 week
* Model Development - Est. 7 weeks
    + Collect Data
    + Exploratory Data Analysis
    + Feature Generation/Selection
    + Train and Validate Model
* Model Deployment - Est. 2 weeks

In addition, there would be an on going Model Management and Maintenance after the deployment of the model.

## Cost Estimate

Besides the development cost of the project, there will be cost associated with the ongoing deployment of the system and the maintenance of both the model and the deployed solution. These estimates are

* Development: Time and Material, estimated 2 Man-Months of development
* Web Server Charges for a small clound instance: Monthly
* Maintenace and Support for the Model and the Server: Annually, 20% of Development Cost


