---
title: "Model Tuning"
author:
  - name: Hakan Egeli
  - name: Soumyendu Sarkar
date: 'May 14, 2018'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), '../reports/', 'step-06-tuning.html')) })
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "..")
```


```{r, echo=FALSE, include = FALSE}

# ProjectTemplate will autoload the data and also create training and test datasets

cwd <- getwd()
setwd("..")

library('ProjectTemplate')
load.project()

setwd(cwd)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
require(e1071)
require(ggplot2)
require(gridExtra)
require(caret)
require(randomForest)

library(ROCR)
library(Hmisc)

# for multinom and nnet methods
library(nnet)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# optional parallelism to be used by caret's trainControl 
library(doParallel);

cl <- makeCluster(detectCores())
registerDoParallel(cl)

```

## Tuning the Final Model

```{r, echo=FALSE, warning=FALSE}

control <- trainControl(method="repeatedcv", number=5, repeats=3, classProbs=TRUE, allowParallel=TRUE)

```

```{r}

model_rf <- train(CreditLimitCategory ~ JBTRating + CreditLimitLocked + SalesCurrentYr + SalesLastYr + DesignBandSalesLast12Mo + NumberOfStoreLocations + AvgDaysOfPayCategory + ReturnedPaymentCount + RuralUrbanContinuumCode + MetroIndicator + MedianEarnings + MedianIncomeHouseholds - 1, data=dataset_train, method="rf", metric="Accuracy", trControl=control, tuneGrid=data.frame(.mtry=19))

```

```{r, echo=FALSE, warning=FALSE}

model_rf$results

```

```{r, warning=FALSE}

predictions <- predict(model_rf, newdata=dataset_test)
cm <- confusionMatrix(dataset_test$CreditLimitCategory, predictions)

```

```{r, echo=FALSE, warning=FALSE}

ggplot(data = data.frame(cm$table), aes(x=Prediction, y=Reference)) +
  geom_tile(aes(fill=Freq)) + 
  scale_fill_gradient(low = "white", high = "steelblue") +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  xlab("Predictions") +
  ylab("Ground Truth (Observations)") +
  geom_text(aes(label = Freq), size = 2) +
  ggtitle("Random Forest Confusion Matrix")

```

```{r, echo=FALSE}

cm$byClass[,c("Sensitivity", "Specificity", "Precision", "Recall")]

```
```{r, echo=FALSE, warning=FALSE, message=FALSE}

predictions <- predict(model_rf, newdata=dataset_test, type = "prob")

```


```{r, echo=FALSE}
df <- setNames(data.frame(matrix(ncol = 5, nrow = 0)), c("class_name", "x.values", "y.values", "x.name", "y.name"))

classifications <- as.character(model_rf$levels)

for (classification in classifications) {

  pred <- prediction(predictions[, classification], ifelse(dataset_test$CreditLimitCategory == classification, 1, 0)) 
  perf <- performance(pred, "tpr", "fpr")

  df <- bind_rows(df,tibble(class_name=classification,
               x.values=perf@x.values[[1]],
               y.values=perf@y.values[[1]],
               x.name=perf@x.name,
               y.name=perf@y.name))
}

ggplot(df) + 
  geom_point(aes(x = x.values, y = y.values)) +
  facet_wrap("class_name") + 
  xlab(perf@x.name) + 
  ylab(perf@y.name)

```

```{r, echo=FALSE}
df <- setNames(data.frame(matrix(ncol = 5, nrow = 0)), c("class_name", "x.values", "y.values", "x.name", "y.name"))

classifications <- as.character(model_rf$levels)

for (classification in classifications) {

  pred <- prediction(predictions[, classification], ifelse(dataset_test$CreditLimitCategory == classification, 1, 0)) 
  perf <- performance(pred, "sens", "spec")

  df <- bind_rows(df,tibble(class_name=classification,
               x.values=perf@x.values[[1]],
               y.values=perf@y.values[[1]],
               x.name=perf@x.name,
               y.name=perf@y.name))
}

ggplot(df) + 
  geom_point(aes(x = x.values, y = y.values)) +
  facet_wrap("class_name") + 
  xlab(perf@x.name) + 
  ylab(perf@y.name)

```


```{r, echo=FALSE, include=FALSE}

# save the model as a file to be used in the model package
#saveRDS(model_rf, "../data/final_model.rds")

# save the test data to be included in the model package
#save(dataset_test, file = "../data/creditlimittestdata.rda")

```

```{r, echo=FALSE}

stopCluster(cl)

```
